openapi: 3.0.3
info:
  title: SkyFollower Aircraft and Operator Microservice
  description: Aircraft Registration and Operator Information
  version: 1.0.0
servers:
  - url: 'http://{domain}:{port}'
    variables:
      domain:
        default: my.web.server.lan
        description: Domain or IP address of the microservice
      port:
        default: "8480"
        description: Port the microservice is listening

security:
  - ApiKeyAuth: []

tags:
  - name: Aircraft and Registration Data
  - name: Airline Operator Data

paths:

  /operator:
    get:
      deprecated: true
      tags:
       - Airline Operator Data
      description: Retrieve airline operator information by ICAO airline designator.
      summary: Retrieve airline operator information
      security:
        - ApiKeyAuth: []
      parameters:
        - in: query
          name: airline_designator
          schema:
            $ref: '#/components/schemas/icao_airline_designator'
          description: ICAO airline designator, case insensitive
          example: DAL
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/operator_response'
              examples:
                British Airways:
                  $ref: '#/components/examples/operator_BAW'
                Delta Air Lines:
                  $ref: '#/components/examples/operator_DAL'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/operator_invalid_request'
        401:
          description: Unauthorized
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
  
    post:
      tags:
       - Airline Operator Data
      description: Create a new airline operator
      summary: Create a new airline operator
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/new_operator_request'
            examples:
              Britsh Airways:
                $ref: '#/components/examples/create_operator_BAW'
      responses:
        204:
          description: OK
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/operator_invalid_request'
        401:
          description: Unauthorized
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

  /operator/{airline_designator}:
    get:
      tags:
       - Airline Operator Data
      description: Retrieve airline operator information by ICAO airline designator
      summary: Retrieve airline operator information
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/icao_airline_designator'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/operator_response'
              examples:
                British Airways:
                  $ref: '#/components/examples/operator_BAW'
                Delta Air Lines:
                  $ref: '#/components/examples/operator_DAL'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/operator_invalid_request'
        401:
          description: Unauthorized
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

    patch:
      tags:
       - Airline Operator Data
      description: Update an existing airline operator information by ICAO airline designator
      summary: Update airline operator information
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/icao_airline_designator'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/update_operator_request'
            examples:
              Delta Air Lines:
                $ref: '#/components/examples/update_operator_DAL'
      responses:
        204:
          description: OK
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/operator_invalid_request'
        401:
          description: Unauthorized
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'

    delete:
      tags:
       - Airline Operator Data
      description: Delete an airline operator by ICAO airline designator
      summary: Delete airline operator
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/icao_airline_designator'
      responses:
        204:
          description: OK
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/operator_invalid_request'
        401:
          description: Unauthorized
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'


  /registration/registration/{registration}:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information
      summary: Retrieve an aicraft registration by registration.  Both simple and detailed will be checked, default simple.  If no result is found for simple, a redirect may be provided to check detailed
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/aircraft_registration'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/simple_registration'
                  - $ref: '#/components/schemas/detailed_registration'
              examples:
                Simple Registration, United States:
                  $ref: '#/components/examples/simple_registration_US'
                Simple Registration, Canada:
                  $ref: '#/components/examples/simple_registration_Canada'
                Detailed Registration, United States:
                  $ref: '#/components/examples/detailed_registration_US'
                Detailed Registration, Canada:
                  $ref: '#/components/examples/detailed_registration_Canada'
        303:
          description: Redirection to detailed data
          headers:
            location:
              description: URL that should be used for redirection
              schema:
                type: string
            referer:
              description: URL of the page that is referring this redirection
              schema:
                type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
                
  /registration/registration/{registration}/simple:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information
      summary: Retrieve an aicraft registration by registration, returning only simple results
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/aircraft_registration'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/simple_registration'
              examples:
                Simple Registration, United States:
                  $ref: '#/components/examples/simple_registration_US'
                Simple Registration, Canada:
                  $ref: '#/components/examples/simple_registration_Canada'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
                
  /registration/registration/{registration}/detailed:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information
      summary: Retrieve an aicraft registration by registration, returning only detailed results
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/aircraft_registration'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/detailed_registration'
              examples:
                Detailed Registration, United States:
                  $ref: '#/components/examples/detailed_registration_US'
                Detailed Registration, Canada:
                  $ref: '#/components/examples/detailed_registration_Canada'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
             
  /registration/icao_hex/{icao_hex}:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information
      summary: Retrieve an aicraft registration by ICAO hex.  Both simple and detailed will be checked, default simple.  If no result is found for simple, a redirect may be provided to check detailed
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/icao_hex'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/simple_registration'
                  - $ref: '#/components/schemas/detailed_registration'
              examples:
                Simple Registration, United States:
                  $ref: '#/components/examples/simple_registration_US'
                Simple Registration, Canada:
                  $ref: '#/components/examples/simple_registration_Canada'
                Detailed Registration, United States:
                  $ref: '#/components/examples/detailed_registration_US'
                Detailed Registration, Canada:
                  $ref: '#/components/examples/detailed_registration_Canada'
        303:
          description: Redirection to detailed data
          headers:
            location:
              description: URL that should be used for redirection
              schema:
                type: string
            referer:
              description: URL of the page that is referring this redirection
              schema:
                type: string
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
                
  /registration/icao_hex/{icao_hex}/simple:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information
      summary: Retrieve an aicraft registration by ICAO hex, returning only simple results
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/icao_hex'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/simple_registration'
              examples:
                Simple Registration, United States:
                  $ref: '#/components/examples/simple_registration_US'
                Simple Registration, Canada:
                  $ref: '#/components/examples/simple_registration_Canada'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
                
  /registration/icao_hex/{icao_hex}/detailed:
    get:
      tags:
       - Aircraft and Registration Data
      description: Retrieve an aicraft's registration and aircraft type information
      summary: Retrieve an aicraft registration by ICAO hex.  Both simple and detailed will be checked, default simple.
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: '#/components/parameters/icao_hex'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/detailed_registration'
              examples:
                Detailed Registration, United States:
                  $ref: '#/components/examples/detailed_registration_US'
                Detailed Registration, Canada:
                  $ref: '#/components/examples/detailed_registration_Canada'
        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'
              examples:
                Bad Request:
                  $ref: '#/components/examples/registration_invalid_request'
        401:
          description: Unauthorized        
        404:
          description: Not Found
        409:
          description: Unexpected Database Response
        500:
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error_message'


components:

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:

    error_message:
      type: object
      properties:
        error:
          type: string
          description: Message describing the error condition
          example: Unexpected Error

    simple_registration:
      type: object
      properties:
        icao_hex:
          $ref: '#/components/schemas/icao_hex'
        registration:
          $ref: '#/components/schemas/aircraft_registration'

    detailed_registration:
      type: object
      description: A country-specific registration record.  Only the fields below are guaranteed to be provided.  Other data in the object will be formatted per the governmental agency.
      properties:
        icao_hex:
          $ref: '#/components/schemas/icao_hex'
        registration:
          $ref: '#/components/schemas/aircraft_registration'
        aircraft:
          $ref: '#/components/schemas/detailed_aircraft'
        powerplant:
          $ref: '#/components/schemas/detailed_aircraft_power_plant'

    icao_hex:
      type: string
      description: The ICAO hexidecimal unique identifier for this aircraft
      minLength: 6
      maxLength: 6

    aircraft_registration:
      type: string
      description: The registration identifier ("tail number") painted on the side of the aircraft

    detailed_aircraft_power_plant:
      type: object
      description: Information about the aircraft's powerplant(s), country-specific

    detailed_aircraft:
      type: object
      description: Information about the aircraft, country-specific

    icao_airline_designator:
      type: string
      minLength: 3
      maxLength: 3
      description: ICAO airline designator

    operator_response:
      type: object
      properties:
        airline_designator:
          $ref: '#/components/schemas/icao_airline_designator'
        name:
          type: string
          description: Airline name
          maxLength: 255
        callsign:
          type: string
          description: Radio callsign prepended to the flight number
          maxLength: 45
        country:
          maxLength: 45
          type: string
          description: Country of registration
        source:
          $ref: '#/components/schemas/source'
        hash:
          $ref: '#/components/schemas/hash'

    new_operator_request:
      type: object
      properties:
        airline_designator:
          $ref: '#/components/schemas/icao_airline_designator'
        name:
          $ref: '#/components/schemas/operator_name'
        callsign:
          $ref: '#/components/schemas/callsign'          
        country:
          $ref: '#/components/schemas/operator_country'
        source:
          $ref: '#/components/schemas/source'

    update_operator_request:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/operator_name'
        callsign:
          $ref: '#/components/schemas/callsign'          
        country:
          $ref: '#/components/schemas/operator_country'
        source:
          $ref: '#/components/schemas/source'

    operator_name:
      type: string
      description: Airline name
      maxLength: 255

    callsign:
      type: string
      description: Radio callsign prepended to the flight number
      maxLength: 45

    operator_country:
      maxLength: 45
      type: string
      description: Country of registration

    source:
      maxLength: 50
      type: string
      description: Originating data source

    hash:
      minLength: 32
      maxLength: 32
      type: string
      readOnly: true
      description: Unique hash for the data contained in the record, used for easily identifying duplicates     

  
  examples:

    registration_invalid_request:
      description: The registration parameter was empty
      value:
        error: Parameter 'registration' is required.

    operator_invalid_request:
      description: The airline_designator parameter was not provided
      value:
        error: Parameter 'airline_designator' is required.

    simple_registration_US:
      value:
        category: LandPlane
        icao_hex: A8AE7F
        military: false
        powerplant:
            type: Jet
            count: 2
        registration: N659DL
        type_designator: B752
        manufacturer_model: BOEING 757-200
        wake_turbulence_category: Medium

    simple_registration_Canada:
      value:
        category: LandPlane
        icao_hex: C01754
        military: false
        powerplant:
            type: Jet
            count: 2
        registration: C-FIVR
        type_designator: B77W
        manufacturer_model: BOEING 777-300ER
        wake_turbulence_category: Heavy

    detailed_registration_US:
      value:
        city: ATLANTA
        name: 
            - DELTA AIR LINES INC
        state: GA
        region: Southern
        status: Valid Registration
        street: 
          - 1775 M H JACKSON SERVICE RD
          - DEPT 595 AIRCRAFT REGISTRATIONS
        country: US
        aircraft:
            type: Fixed wing multi engine
            model: 757-232
            seats: 178
            weight: Exceeds 20,000lbs
            category: Land
            manufacturer: BOEING
            builder_certification: Type Certificated
        icao_hex: A8AE7F
        powerplant:
            count: 2
        last_action: "2020-07-16"
        postal_code: "303543743"
        registration: N659DL
        certification:
          - None
        serial_number: "24421"
        registrant_type: Corporation
        certificate_issue: "2017-08-30"
        manufactured_year: "1990"
        airworthiness_date: ""
        registration_expiration_date: "2023-08-31"
    
    detailed_registration_Canada:
      value:
        icao_hex: C01754
        registration: C-FIVR
        use: Commercial
        owners:
          - city: Dorval
            name: Air Canada
            type: Entity
            region: Quebec
            street:
              - Centre Air Canada, zip 1012
              - P.O. Box 9000, Station Airport
            country: CANADA
            province: Quebec
            postal_code: H4Y1C2
            mail_recipient: Yes
        status: Registered
        aircraft:
          model: 777-333ER
          weight: 351534.0
          category: Aeroplane
          manufacture_type: Manufactured
          eligibility_basis: CAR Standard 507.02, 507.03 - Type Certificate
          manufacturer_name: THE BOEING COMPANY
          country_manufactured: U.S.A.
          type_certificate_number:  A246
          manufacturer_name_common: Boeing
        issue_date: "2009-02-13"
        powerplant: 
          count: 2
          category: Turbo Fan
        import_date: "2009-01-20"
        modified_date: "2009-02-13"
        serial_number: "35241"
        effective_date: "2009-02-13"
        base_operations:
            base: Montr√©al Trudeau
            country: CANADA
            province: Quebec
        flight_authority: Certificate of Airworthiness
        manufactured_date: "2008-01-01"

    operator_BAW:
      value:
        airline_designator: BAW
        name: British Airways
        callsign: SPEEDBIRD
        country: United Kingdom
        source: Mictronics-IndexedDB
        hash: 26053d5ea8a1609ed4d25de2732eb63d

    operator_DAL:
      value:
        airline_designator: DAL
        name: Delta Air Lines
        callsign: DELTA
        country: United States
        source: Mictronics-IndexedDB
        hash: 4c78deb4ed8c275b31cc894f89251565

    create_operator_BAW:
      value:
        airline_designator: BAW
        name: British Airways
        callsign: SPEEDBIRD
        country: United Kingdom
        source: Mictronics-IndexedDB

    update_operator_DAL:
      value:
        name: Delta Air Lines
        callsign: DELTA
        country: United States
        source: Mictronics-IndexedDB


  parameters:

  #description: If specified, detailed information about the aircraft's registration is returned from a governmental source of authority

    icao_airline_designator:
      in: path
      name: airline_designator
      description: ICAO airline designator, case insensitive
      example: DAL
      required: true
      schema:
        $ref: '#/components/schemas/icao_airline_designator'

    icao_hex:
      in: path
      name: icao_hex
      example: A8AE7F
      required: true
      schema:
        $ref: '#/components/schemas/icao_hex'

    aircraft_registration:
      in: path
      name: registration
      description: Aircraft's registration, case insensitive
      example: N659DL
      required: true
      schema:
        $ref: '#/components/schemas/aircraft_registration'

    referer:
      in: header
      name: referer
      schema:
        type: string

    location:
      in: header
      name: location
      schema:
        type: string
